#!/usr/bin/env python3
"""Generate Pioneer Trail's non-title pixel scenes from deterministic geometry.

The title is generated separately. This script reuses its canonical wagon and
ox shapes and owns all non-title terrain, actors, landmarks, and minigame assets.
"""

from __future__ import annotations

import argparse
from pathlib import Path

from gen_logo import OX, WAGON, sprite


ROOT = Path(__file__).resolve().parents[1]
ART = ROOT / "crates" / "data" / "art"
PALETTE = {"K": "#000000", "W": "#FFFFFF", "G": "#1BCB01", "V": "#E434FE", "O": "#F26A00", "B": "#1B9AFE"}


class Canvas:
    def __init__(self, width: int = 80, height: int = 32) -> None:
        self.width, self.height = width, height
        self.rows = [["." for _ in range(width)] for _ in range(height)]

    def put(self, x: int, y: int, color: str) -> None:
        if 0 <= x < self.width and 0 <= y < self.height:
            self.rows[y][x] = color

    def rect(self, x: int, y: int, width: int, height: int, color: str) -> None:
        for yy in range(y, y + height):
            for xx in range(x, x + width):
                self.put(xx, yy, color)

    def line(self, x0: int, y0: int, x1: int, y1: int, color: str) -> None:
        dx, sx = abs(x1 - x0), 1 if x0 < x1 else -1
        dy, sy = -abs(y1 - y0), 1 if y0 < y1 else -1
        error = dx + dy
        while True:
            self.put(x0, y0, color)
            if (x0, y0) == (x1, y1):
                return
            twice = 2 * error
            if twice >= dy:
                error += dy
                x0 += sx
            if twice <= dx:
                error += dx
                y0 += sy

    def polygon(self, points: list[tuple[int, int]], color: str) -> None:
        min_y = max(0, min(y for _, y in points))
        max_y = min(self.height - 1, max(y for _, y in points))
        for y in range(min_y, max_y + 1):
            intersections = []
            for (x1, y1), (x2, y2) in zip(points, points[1:] + points[:1]):
                if (y1 <= y < y2) or (y2 <= y < y1):
                    intersections.append(x1 + (y - y1) * (x2 - x1) / (y2 - y1))
            intersections.sort()
            for left, right in zip(intersections[::2], intersections[1::2]):
                for x in range(round(left), round(right) + 1):
                    self.put(x, y, color)

    def ellipse(self, cx: int, cy: int, rx: int, ry: int, color: str) -> None:
        for y in range(cy - ry, cy + ry + 1):
            for x in range(cx - rx, cx + rx + 1):
                if (x - cx) ** 2 * ry ** 2 + (y - cy) ** 2 * rx ** 2 <= rx ** 2 * ry ** 2:
                    self.put(x, y, color)

    def save(self, name: str) -> None:
        lines = ["# Generated by assets/gen_scenes.py. Do not hand-edit."]
        lines.extend("".join(row) for row in self.rows)
        (ART / name).write_text("\n".join(lines) + "\n")

    def blit(self, art: list[str], x0: int = 0, y0: int = 0) -> None:
        for y, row in enumerate(art):
            for x, pixel in enumerate(row):
                self.put(x0 + x, y0 + y, pixel)


def ground(c: Canvas, color: str = "G") -> None:
    c.rect(0, 30, 80, 1, color)
    for x in range(80):
        c.put(x, 31, color if x % 5 else "K")


def sky_band(c: Canvas, color: str, y: int = 5, width: int = 2) -> None:
    c.rect(0, y, 80, width, color)
    for x in range(0, 80, 9):
        c.put(x, y + width - 1, ".")


def pine(c: Canvas, x: int, base: int, height: int) -> None:
    for level, y in enumerate(range(base - height, base, 3)):
        half = 1 + level // 2
        c.polygon([(x, y), (x - half - 2, y + 4), (x + half + 2, y + 4)], "G")
    c.rect(x, base, 1, 2, "O")


def mountain(c: Canvas, x: int, peak: int, base: int, half: int, color: str = "B") -> None:
    c.polygon([(x - half, base), (x, peak), (x + half, base)], color)
    cap = max(2, half // 3)
    c.polygon([(x, peak), (x - cap, peak + cap + 2), (x, peak + cap), (x + cap, peak + cap + 2)], "W")


def terrain() -> None:
    c = Canvas(); sky_band(c, "B", 7, 2)
    for x in range(4, 80, 11):
        c.line(x, 27, x + 2, 24, "G")
        c.line(x + 2, 24, x + 4, 27, "G")
    ground(c); c.save("terrain_plains.px")

    c = Canvas(); sky_band(c, "V", 6, 2)
    c.polygon([(0, 28), (0, 20), (13, 16), (28, 22), (44, 15), (60, 20), (80, 14), (80, 28)], "G")
    for x in range(5, 80, 13): c.rect(x, 23 - (x % 3), 2, 2, "G")
    ground(c); c.save("terrain_hills.px")

    c = Canvas(); sky_band(c, "B", 4, 2)
    mountain(c, 13, 10, 30, 17); mountain(c, 39, 5, 30, 23); mountain(c, 66, 11, 30, 19)
    for x in range(4, 80, 12): pine(c, x, 29, 7 + x % 4)
    ground(c); c.save("terrain_mountains.px")

    c = Canvas(); sky_band(c, "V", 5, 2)
    c.polygon([(0, 29), (0, 23), (20, 19), (38, 23), (58, 18), (80, 22), (80, 29)], "O")
    for x in range(7, 80, 15): c.ellipse(x, 26, 4, 1, "O")
    ground(c, "O"); c.save("terrain_desert.px")

    c = Canvas(); sky_band(c, "B", 6, 2)
    for x, h in [(5, 13), (14, 10), (24, 16), (36, 11), (47, 15), (59, 12), (70, 17), (78, 10)]: pine(c, x, 29, h)
    ground(c); c.save("terrain_forest.px")

    c = Canvas(); sky_band(c, "B", 5, 2)
    c.polygon([(0, 29), (0, 18), (15, 14), (29, 19), (44, 13), (60, 19), (80, 15), (80, 29)], "G")
    c.polygon([(30, 30), (38, 21), (48, 16), (54, 12), (62, 8), (68, 7), (68, 30)], "B")
    for y in range(11, 30, 5): c.line(50 + y // 3, y, 63 + y // 4, y + 1, "W")
    ground(c); c.save("terrain_river_valley.px")


def river_scene(name: str, shift: int, bank: str = "G") -> None:
    c = Canvas(); sky_band(c, "B", 5, 2)
    c.rect(0, 7, 80, 23, bank)
    points = [(shift + 25, 30), (shift + 7, 24), (shift + 26, 18), (shift + 47, 12), (shift + 33, 7), (shift + 55, 7), (shift + 68, 13), (shift + 48, 20), (shift + 30, 26), (shift + 45, 30)]
    c.polygon(points, "B")
    for y in range(10, 29, 4):
        x = (shift + 34 + y * 3) % 60 + 10
        c.line(x, y, min(78, x + 9), y + 1, "W")
        c.put(min(79, x + 9), y, "W")
    for x in range(4, 80, 15):
        c.rect(x, 26, 2, 3, "O")
        c.polygon([(x + 1, 18), (x - 3, 26), (x + 5, 26)], "G")
    ground(c, bank); c.save(name)


def forts() -> None:
    specs = [("fort_kearney.px", 10, 51, 18), ("fort_laramie.px", 7, 59, 14), ("fort_bridger.px", 13, 54, 16), ("fort_hall.px", 9, 57, 17), ("fort_boise.px", 15, 49, 15), ("fort_walla_walla.px", 8, 61, 13)]
    for name, left, right, tower in specs:
        c = Canvas(); sky_band(c, "B", 5, 2)
        c.rect(left, 18, right - left, 11, "O")
        # Corner bastions and alternating palisade tips make every fort read as defended.
        c.polygon([(left - 5, 29), (left, 14), (left + 5, 29)], "O")
        c.polygon([(right - 5, 29), (right, 14), (right + 5, 29)], "O")
        for x in range(left, right, 3):
            c.polygon([(x, 18), (x + 1, 15), (x + 2, 18)], "W")
        gate = (left + right) // 2
        c.rect(gate - 4, 22, 9, 7, "W"); c.rect(gate - 2, 25, 5, 4, "O")
        c.rect(tower, 8, 2, 10, "O"); c.line(tower + 2, 8, tower + 8, 10, "W"); c.rect(tower + 7, 10, 5, 3, "B")
        for x in range(left + 7, right - 5, 11): c.rect(x, 21, 3, 3, "W")
        ground(c); c.save(name)


def landmarks() -> None:
    c = Canvas(); sky_band(c, "B", 5, 2)
    c.polygon([(12, 29), (28, 23), (35, 19), (36, 6), (43, 6), (45, 19), (55, 23), (70, 29)], "O")
    c.rect(38, 7, 3, 14, "W"); c.polygon([(34, 21), (40, 15), (47, 23)], "O"); ground(c); c.save("chimney_rock.px")

    c = Canvas(); sky_band(c, "V", 6, 2)
    c.ellipse(41, 22, 27, 8, "O"); c.ellipse(42, 18, 17, 5, "O"); c.line(25, 18, 34, 14, "W"); c.line(35, 14, 49, 15, "W"); ground(c); c.save("independence_rock.px")

    c = Canvas(); sky_band(c, "B", 4, 2)
    mountain(c, 16, 9, 30, 18); mountain(c, 64, 9, 30, 18)
    c.polygon([(25, 30), (34, 20), (46, 20), (55, 30)], "G"); c.line(36, 22, 44, 22, "W"); ground(c); c.save("south_pass.px")

    c = Canvas(); sky_band(c, "B", 6, 2)
    c.rect(0, 27, 80, 3, "O"); c.ellipse(40, 25, 26, 6, "B")
    for x in range(16, 66, 10): c.rect(x, 17, 3, 9, "O")
    for x in range(20, 63, 11): c.line(x, 22, x + 4, 20, "W")
    ground(c); c.save("soda_springs.px")

    c = Canvas(); sky_band(c, "B", 4, 2)
    for x, peak, half in [(10, 14, 12), (27, 8, 16), (47, 12, 15), (68, 6, 18)]: mountain(c, x, peak, 30, half)
    for x in range(5, 80, 12): pine(c, x, 29, 7)
    ground(c); c.save("blue_mountains.px")

    c = Canvas(); sky_band(c, "V", 6, 2)
    c.polygon([(0, 10), (16, 14), (16, 29), (0, 29)], "O"); c.polygon([(80, 8), (62, 13), (62, 29), (80, 29)], "O")
    c.polygon([(14, 30), (28, 22), (50, 22), (67, 30)], "B")
    for y in range(24, 30, 2): c.line(27, y, 52, y, "W")
    ground(c); c.save("the_dalles.px")

    c = Canvas(); sky_band(c, "B", 5, 2)
    c.polygon([(29, 30), (37, 20), (46, 14), (54, 15), (63, 20), (71, 30)], "B")
    for x, h in [(5, 12), (14, 9), (24, 14), (66, 12), (75, 15)]: pine(c, x, 29, h)
    c.rect(34, 24, 10, 5, "O"); c.polygon([(32, 24), (39, 19), (46, 24)], "W"); ground(c); c.save("willamette.px")


def map_oregon() -> None:
    c = Canvas(); c.rect(0, 0, 80, 32, "K")
    # Rivers frame a clear westward route across the map.
    c.line(9, 0, 14, 31, "B"); c.line(58, 0, 63, 31, "B"); c.line(0, 25, 80, 19, "B")
    route = [(8, 27), (16, 25), (22, 23), (31, 22), (39, 19), (46, 17), (51, 13), (57, 11), (65, 9), (72, 6)]
    for a, b in zip(route, route[1:]): c.line(*a, *b, "W")
    for x, y in route: c.ellipse(x, y, 1, 1, "O")
    c.ellipse(46, 17, 2, 2, "G"); c.save("map_oregon.px")


def animal(c: Canvas, kind: str, step: int) -> None:
    # Each profile uses a deliberately different outline, not a shared body rectangle.
    if kind == "buffalo":
        c.polygon([(1, 6), (3, 3), (5, 2), (7, 4), (10, 4), (12, 5), (14, 5), (15, 7), (13, 8), (4, 8)], "O")
        c.rect(2, 5, 2, 3, "O"); c.put(1, 4, "W"); c.put(3, 3, "W"); c.put(12, 5, "W")
        legs = [(4, 8), (7, 8), (11, 8), (13, 8)]
    elif kind == "bear":
        c.ellipse(7, 6, 6, 3, "O"); c.ellipse(12, 6, 3, 2, "O"); c.put(11, 3, "O"); c.put(13, 4, "W"); c.put(15, 6, "K")
        legs = [(3, 8), (6, 8), (10, 8), (13, 8)]
    elif kind == "deer":
        c.polygon([(2, 7), (4, 4), (9, 4), (11, 5), (12, 3), (14, 2), (15, 4), (13, 6), (11, 7), (5, 8)], "O")
        c.put(14, 1, "W"); c.put(12, 2, "W"); c.put(15, 5, "W")
        legs = [(4, 8), (7, 8), (10, 8), (12, 8)]
    elif kind == "rabbit":
        c.ellipse(8, 7, 5, 2, "O"); c.ellipse(12, 5, 2, 2, "O"); c.rect(11, 0, 1, 4, "W"); c.rect(13, 0, 1, 4, "W"); c.put(14, 5, "W")
        legs = [(6, 8), (9, 8)]
    else:
        c.ellipse(8, 6, 4, 3, "O"); c.ellipse(12, 6, 2, 2, "O"); c.polygon([(4, 7), (0, 3), (1, 0), (4, 2), (6, 5)], "O")
        c.put(13, 5, "W"); legs = [(7, 8), (10, 8)]
    for index, (x, y) in enumerate(legs):
        c.put(x + ((index + step) % 2), y, "K")
        c.put(x + ((index + step) % 2), 9, "K")


def hunting() -> None:
    for kind in ["buffalo", "bear", "deer", "rabbit", "squirrel"]:
        for step in range(2):
            c = Canvas(16, 10); animal(c, kind, step); c.save(f"{kind}_{step}.px")
    for step in range(2):
        c = Canvas(13, 11)
        c.line(0, 5, 4, 5, "W"); c.line(8, 5, 12, 5, "W"); c.line(6, 0, 6, 3, "W"); c.line(6, 7, 6, 10, "W")
        c.ellipse(6, 5, 2 + step, 2 + step, "O"); c.put(6, 5, "W"); c.save(f"crosshair_{step}.px")


def actors() -> None:
    """Turn the canonical logo actors into independently animated sprites."""
    wagon = sprite(WAGON)
    ox = sprite(OX)
    wheel_centers = (6, 33)
    for frame in range(4):
        c = Canvas(40, 20)
        c.blit(wagon)
        # Keep the full canonical wagon silhouette. Alternate a plus and an X
        # inside each white rim; the canopy's center rib shifts one pixel to
        # give the body a restrained trail bob without changing its footprint.
        for center in wheel_centers:
            if frame % 2 == 0:
                for x, y in [(center, 13), (center, 14), (center, 15), (center - 1, 15), (center + 1, 15), (center, 16), (center, 17)]:
                    c.put(x, y, "K")
            else:
                for x, y in [(center - 1, 14), (center + 1, 14), (center, 15), (center - 1, 16), (center + 1, 16)]:
                    c.put(x, y, "K")
        rib_x = 19 + (1 if frame in (1, 2) else 0)
        for y in range(4, 8):
            c.put(rib_x, y, "K")
        c.save(f"wagon_{frame}.px")

    for frame in range(2):
        c = Canvas(20, 10)
        c.blit(ox)
        # Original horns and body stay intact; only the four hooves trade
        # forward/back positions for a walking cycle.
        for x in range(20):
            if c.rows[9][x] == "K":
                c.put(x, 9, ".")
        hooves = (3, 4, 7, 8, 14, 15, 18, 19) if frame == 0 else (4, 5, 7, 8, 13, 14, 17, 18)
        for x in hooves:
            c.put(x, 9, "K")
        c.save(f"ox_{frame}.px")


def rafting() -> None:
    c = Canvas(12, 6); c.polygon([(1, 3), (3, 1), (9, 1), (11, 3), (9, 5), (3, 5)], "O")
    c.rect(3, 2, 6, 2, "W"); c.line(1, 0, 10, 5, "K"); c.save("raft.px")
    for index, points in enumerate([[(0, 3), (2, 0), (5, 3)], [(0, 3), (3, 0), (5, 3)], [(0, 3), (2, 1), (5, 3)]]):
        c = Canvas(6, 4); c.polygon(points + [(5, 3), (0, 3)], "W"); c.put(2 + index % 2, 2, "B"); c.save(f"rock_{index}.px")
    c = Canvas(8, 10)
    for y, row in enumerate(["........", "...WW...", "..WWWW..", ".WWWWWW.", ".WWKWWW.", ".WKKKWW.", ".WWKWWW.", ".WWWWWW.", ".WWWWWW.", "WWWWWWWW"]):
        for x, pixel in enumerate(row): c.put(x, y, pixel)
    c.save("tombstone.px")


def generate() -> None:
    terrain()
    for name, shift, bank in [("kansas_river.px", 0, "G"), ("big_blue.px", 8, "G"), ("green_river.px", 15, "G"), ("snake_river.px", 23, "O"), ("columbia.px", 31, "O")]:
        river_scene(name, shift, bank)
    forts(); landmarks(); map_oregon(); hunting(); actors(); rafting()


def contact_sheet(path: Path) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    assets = sorted(ART.glob("*.px"))
    cell_w, cell_h, scene_scale, columns = 184, 94, 2, 4
    rows = (len(assets) + columns - 1) // columns
    out = [f'<svg xmlns="http://www.w3.org/2000/svg" width="{cell_w * columns}" height="{cell_h * rows}" viewBox="0 0 {cell_w * columns} {cell_h * rows}">', '<rect width="100%" height="100%" fill="#000000"/>']
    for index, asset in enumerate(assets):
        x0, y0 = (index % columns) * cell_w, (index // columns) * cell_h
        rows_px = [line for line in asset.read_text().splitlines() if not line.startswith("#")]
        scale = scene_scale if len(rows_px[0]) >= 40 else 6
        out.append(f'<text x="{x0 + 4}" y="{y0 + 11}" fill="#fff" font-family="monospace" font-size="9">{asset.stem}</text>')
        for y, row in enumerate(rows_px):
            for x, pixel in enumerate(row):
                if pixel != ".":
                    out.append(f'<rect x="{x0 + 4 + x * scale}" y="{y0 + 15 + y * scale}" width="{scale}" height="{scale}" fill="{PALETTE[pixel]}"/>')
    out.append("</svg>")
    path.write_text("\n".join(out))


if __name__ == "__main__":
    parser = argparse.ArgumentParser()
    parser.add_argument("--contact-sheet", type=Path)
    args = parser.parse_args()
    generate()
    if args.contact_sheet:
        contact_sheet(args.contact_sheet)
